// <auto-generated>
// 由 tools/make-glyphs.py 从 design/ui-mock.html 的 SVG 图标族生成，**别手改**。
// 规格（UI 手册 §6）：24x24 视框、1.6 描边、圆头圆角、无填充、stroke=currentColor
//（WPF 这边就是让 Path.Stroke 跟着 Foreground/资源走）。渲染尺寸 = 图标格 x 50%。
// </auto-generated>
using System;
using System.Collections.Generic;
using System.IO;
using System.Windows.Media;

namespace Paperwork.Data;

/// <summary>
/// 预设图标图形 + 「扩展名 -&gt; 图标」映射。
///
/// **为什么是预设而不是解 Shell 图标**：Shell 图标各软件各画各的，32px 下有扁有圆、有彩色有单色，
/// 混在一起永远不可能统一。改成按文件类型给同一支笔画的图形，风格天然是齐的。
/// 真实图标仍然保留，但只给两类：程序/快捷方式（<see cref="IsProgram"/>）与用户显式「改图标」指定的，
/// 其余文件类一律预设线稿（见 <see cref="TileVm.WantsShellIcon"/>）。
/// </summary>
public static class Glyphs
{
    /// <summary>shell（24x24 视框）</summary>
    public static readonly Geometry Shell = Geometry.Parse("M5.9,4.5 H18.1 A2.4,2.4 0 0 1 20.5,6.9 V17.1 A2.4,2.4 0 0 1 18.1,19.5 H5.9 A2.4,2.4 0 0 1 3.5,17.1 V6.9 A2.4,2.4 0 0 1 5.9,4.5 Z M3.5 9h17M7 6.6h.01M9.6 6.6h.01");
    /// <summary>doc（24x24 视框）</summary>
    public static readonly Geometry Doc = Geometry.Parse("M6 3.4h7.4L19 9v11.6H6z M13.2 3.6V9H19M9 13h6M9 16.4h6");
    /// <summary>note（24x24 视框）</summary>
    public static readonly Geometry Note = Geometry.Parse("M6.6,3.6 H17.4 A2.2,2.2 0 0 1 19.6,5.8 V18.2 A2.2,2.2 0 0 1 17.4,20.4 H6.6 A2.2,2.2 0 0 1 4.4,18.2 V5.8 A2.2,2.2 0 0 1 6.6,3.6 Z M8 8.4h8M8 12h8M8 15.6h5");
    /// <summary>code（24x24 视框）</summary>
    public static readonly Geometry Code = Geometry.Parse("M9 7l-5 5 5 5M15 7l5 5-5 5");
    /// <summary>pdf（24x24 视框）</summary>
    public static readonly Geometry Pdf = Geometry.Parse("M6 3.4h7.4L19 9v11.6H6z M13.2 3.6V9H19 M8.6 17.4v-4.2h1.3a1.3 1.3 0 0 1 0 2.6H8.6M13.4 17.4v-4.2h1a2.1 2.1 0 0 1 0 4.2z");
    /// <summary>picture（24x24 视框）</summary>
    public static readonly Geometry Picture = Geometry.Parse("M5.6,4.8 H18.4 A2.4,2.4 0 0 1 20.8,7.2 V16.8 A2.4,2.4 0 0 1 18.4,19.2 H5.6 A2.4,2.4 0 0 1 3.2,16.8 V7.2 A2.4,2.4 0 0 1 5.6,4.8 Z M6.8,9.8 A1.8,1.8 0 1 1 10.4,9.8 A1.8,1.8 0 1 1 6.8,9.8 Z M3.6 16.2l4.6-4 4 3.5 2.8-2.4 4.6 4");
    /// <summary>music（24x24 视框）</summary>
    public static readonly Geometry Music = Geometry.Parse("M9 17.6V5.4l10-1.9v12.2 M4.1,17.6 A2.5,2.5 0 1 1 9.1,17.6 A2.5,2.5 0 1 1 4.1,17.6 Z M14.1,15.7 A2.5,2.5 0 1 1 19.1,15.7 A2.5,2.5 0 1 1 14.1,15.7 Z");
    /// <summary>video（24x24 视框）</summary>
    public static readonly Geometry Video = Geometry.Parse("M5.2,5.6 H13 A2.4,2.4 0 0 1 15.4,8 V16 A2.4,2.4 0 0 1 13,18.4 H5.2 A2.4,2.4 0 0 1 2.8,16 V8 A2.4,2.4 0 0 1 5.2,5.6 Z M15.4 10.4l5.8-3.2v9.6l-5.8-3.2z");
    /// <summary>sheet（24x24 视框）</summary>
    public static readonly Geometry Sheet = Geometry.Parse("M6.2,3.6 H17.8 A2.2,2.2 0 0 1 20,5.8 V18.2 A2.2,2.2 0 0 1 17.8,20.4 H6.2 A2.2,2.2 0 0 1 4,18.2 V5.8 A2.2,2.2 0 0 1 6.2,3.6 Z M4 9h16M4 14.6h16M10 3.8v16.4M15 3.8v16.4");
    /// <summary>archive（24x24 视框）</summary>
    public static readonly Geometry Archive = Geometry.Parse("M4.6,4.6 H19.4 A1.4,1.4 0 0 1 20.8,6 V7.4 A1.4,1.4 0 0 1 19.4,8.8 H4.6 A1.4,1.4 0 0 1 3.2,7.4 V6 A1.4,1.4 0 0 1 4.6,4.6 Z M4.8 8.8v9a1.6 1.6 0 0 0 1.6 1.6h11.2a1.6 1.6 0 0 0 1.6-1.6v-9M10 12.6h4");
    /// <summary>folder（24x24 视框）</summary>
    public static readonly Geometry Folder = Geometry.Parse("M3.2 7.4A2.4 2.4 0 0 1 5.6 5h3.2l2 2.4h7.6A2.4 2.4 0 0 1 20.8 9.8v6.8A2.4 2.4 0 0 1 18.4 19H5.6a2.4 2.4 0 0 1-2.4-2.4z");
    /// <summary>drop（24x24 视框）</summary>
    public static readonly Geometry Drop = Geometry.Parse("M12 3.6v11M7.6 10.4L12 14.8l4.4-4.4 M4.4 16.4v2.4a1.8 1.8 0 0 0 1.8 1.8h11.6a1.8 1.8 0 0 0 1.8-1.8v-2.4");
    /// <summary>more（24x24 视框）</summary>
    public static readonly Geometry More = Geometry.Parse("M5 12V5a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1h-6 M11 13l8-8M13 5h6v6");

    /// <summary>
    /// 扩展名 -&gt; 图标名。**顺序即优先级**：程序/快捷方式排在最前，
    /// <see cref="IsProgram"/> 与 <see cref="ForPath"/> 共用这张表，两边不可能跑偏。
    /// </summary>
    private static readonly (string Name, string[] Exts)[] Map =
    {
        ("shell", new[] { ".exe", ".lnk", ".msi", ".bat", ".cmd", ".ps1", ".appref" }),
        ("pdf", new[] { ".pdf" }),
        ("picture", new[] { ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".svg", ".webp", ".ico" }),
        ("music", new[] { ".mp3", ".wav", ".flac", ".m4a", ".aac", ".ogg" }),
        ("video", new[] { ".mp4", ".mkv", ".avi", ".mov", ".wmv", ".webm" }),
        ("sheet", new[] { ".xls", ".xlsx", ".csv", ".tsv" }),
        ("archive", new[] { ".zip", ".rar", ".7z", ".tar", ".gz", ".iso" }),
        ("note", new[] { ".txt", ".md", ".log", ".json", ".xml", ".yaml", ".toml" }),
        ("code", new[] { ".cs", ".js", ".ts", ".py", ".java", ".html", ".css", ".xaml", ".go", ".rs", ".cpp", ".h" }),
        ("doc", new[] { ".doc", ".docx", ".ppt", ".pptx", ".rtf", ".odt", ".odp" }),
    };

    /// <summary>兜底：其它一切文件都是"一张纸"。</summary>
    public static Geometry Fallback => Doc;

    private static readonly Dictionary<string, Geometry> ByName = new(StringComparer.Ordinal)
    {
        ["shell"] = Shell,
        ["doc"] = Doc,
        ["note"] = Note,
        ["code"] = Code,
        ["pdf"] = Pdf,
        ["picture"] = Picture,
        ["music"] = Music,
        ["video"] = Video,
        ["sheet"] = Sheet,
        ["archive"] = Archive,
        ["folder"] = Folder,
        ["drop"] = Drop,
        ["more"] = More
    };

    /// <summary>按类型取预设图形。目录给文件夹形，其它兜底 <c>doc</c>。</summary>
    public static Geometry ForPath(string path, bool isDir)
    {
        if (isDir) return Folder;
        string ext = Path.GetExtension(path ?? string.Empty).ToLowerInvariant();
        if (ext.Length == 0) return Fallback;

        foreach (var (name, exts) in Map)
            if (Array.IndexOf(exts, ext) >= 0) return ByName[name];

        return Fallback;
    }

    /// <summary>
    /// 程序 / 快捷方式：**保留真 Shell 图标**——VS Code / 微信 / Steam 这类图标的辨识度
    /// 就是内容本身，换成统一图形反而丢信息（2026-09-24 用户拍板的替代范围）。
    /// </summary>
    public static bool IsProgram(string path)
    {
        string ext = Path.GetExtension(path ?? string.Empty).ToLowerInvariant();
        return ext.Length > 0 && Array.IndexOf(PROGRAMS, ext) >= 0;
    }

    private static readonly string[] PROGRAMS = { ".exe", ".lnk", ".msi", ".bat", ".cmd", ".ps1", ".appref" };
}
